---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: alpine

outputs:
  - name: release-name

run:
  path: /bin/sh
  args:
    - -c
    - |
      echo "govc" > release-name/name
